name: "Deploy to Heroku"
description: "Deploy an app to Heroku"
branding:
  icon: "upload-cloud"
  color: "purple"
inputs:
  heroku_api_key:
    description: "This will be used for authentication. You can find it in your heroku homepage account settings"
    required: true
  heroku_email:
    description: "Email that you use with heroku"
    required: true
  heroku_app_name:
    description: "The appname to use for deploying/updating"
    required: true
  buildpack:
    description: "An optional buildpack to use when creating the heroku application"
    required: false
  region:
    description: "The region in which you would like to deploy a server"
    required: false
    default: ""
  team:
    description: "If deploying to an organization, then specify the name of the team or organization here"
    required: false
    default: ""
outputs:
  status:
    description: "The Success/Failure of the action"
runs:
  using: "node12"
  main: "index.js"
